### PR TITLE
Add verify workflow and specify node version

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
- Verify with linters and by building the browser extensions on each push.
- Add [web-ext](https://github.com/mozilla/web-ext)
- Specify the same node version we're using with the main app.

### CODE REVIEW

**Comment by Aetherinox** [comment]
Is this one ready to go or are you still adding?

**Comment by HarlemSquirrel** [comment]
This is ready if it looks good to you

**Comment by HarlemSquirrel** [comment]
I can try bumping prettier

**Comment by Aetherinox** [comment]
Thanks. Everything good to go now?

**Comment by HarlemSquirrel** [comment]
> Prettier v3 die on you?

Yeah, led me down dependency hell. Opened new PR to work on node 18 and hopefully prettier 3

**Comment by Aetherinox** [comment]
Trust me, already went through that with KeeWeb.

I lost a week of my life just fixing that mess.

**Pull request merged**
